[build]
# Point to the backend folder
build_dir = "backend"

# Run npm install from the backend folder
build_command = "npm install --prefix backend"

# Start the backend server from the backend folder
start_command = "npm start --prefix backend"

[env]
DATABASE_URL = "mysql://root:GwgFXvjahRiphkCwuwWRlKxXbeGEyMek@turntable.proxy.rlwy.net:13431/railway"
