[build]
# Point to the backend folder
build_dir = "backend"

# Install dependencies inside the backend folder
build_command = "npm install --prefix backend"

# Run the correct start command in the backend folder
start_command = "npm run start --prefix backend"

[env]
DATABASE_URL = "mysql://root:GwgFXvjahRiphkCwuwWRlKxXbeGEyMek@turntable.proxy.rlwy.net:13431/railway"