[build]
# Point to the backend folder
build_dir = "backend"
build_command = "npm install"
start_command = "npm start"

# Optional: If you want to specify specific environment variables
[env]
DATABASE_URL=mysql://root:GwgFXvjahRiphkCwuwWRlKxXbeGEyMek@turntable.proxy.rlwy.net:13431/railway
