[build]
# Point to the backend folder
build_dir = "backend"

# Install dependencies inside the backend folder
build_command = "npm install --prefix backend"

# Use the correct start command for your backend
start_command = "npm run dev --prefix backend"

[env]
DATABASE_URL = "mysql://root:GwgFXvjahRiphkCwuwWRlKxXbeGEyMek@turntable.proxy.rlwy.net:13431/railway"


